title: Dramaking's Blog
markdown: kramdown
url: ""
baseurl: ""

# for atom feed
author:
  name: dramaking
  email: dramaking.lee@gmail.com
  image: "https://avatars0.githubusercontent.com/u/1614604?s=400&u=1f15f4fdd65a32046ff94f160039a98609d86cdf&v=4"
  bio: 中国开发者<b>dramaking</b>
  github: "chasel"

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/
