# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 顾竹君写字的地方
email: chasel.gu@gmail.com
description: 谦卑而执着 羞涩而无畏
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chasel.li" # the base hostname & protocol for your site
twitter_username: chasel
github_username:  chasel

# Build settings
markdown: kramdown
highlighter: true
